[gcp_service_account]
type = "service_account"
project_id = "sphinxai-383621"
private_key_id = "your-private-key-id"
private_key = "your-private-key"
client_email = "sphinxai-transcripcion@sphinxai-383621.iam.gserviceaccount.com"
client_id = "217884455561-p8blknss49hjjigghkpvbd102ujoci3e.apps.googleusercontent.com"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "your-cert-url"

# Add your Google Sheet details
sheet_id = "your-sheet-id"
sheet_range = "Sheet1!A1:J1000"  # Adjust range as needed